### ISSUE TITLE
override template

### ISSUE THREAD

**Issue by h1alexbel** [Blamer-io/hub#1]

**Comment by 0pdd** [comment]
@h1alexbel 5 puzzles [#10](https://github.com/Blamer-io/hub/issues/10), [#11](https://github.com/Blamer-io/hub/issues/11), [#7](https://github.com/Blamer-io/hub/issues/7), [#8](https://github.com/Blamer-io/hub/issues/8), [#9](https://github.com/Blamer-io/hub/issues/9) are still not solved.
