### ISSUE TITLE
sequence diagram

### ISSUE THREAD

**Issue by h1alexbel** [Blamer-io/hub#18]
create a sequence diagram describing all the interaction in the bot, hub, and notification systems

**Comment by h1alexbel** [comment]
@l3r8yJ after closing this ticket we can get back to the coding the hub and notifications system

**Comment by h1alexbel** [comment]
@l3r8yJ please, take a look here

we need a mapping between `Chat ID` and `Token`

![seqence](https://github.com/Blamer-io/hub/assets/83453843/79bb18db-a068-4734-8bd1-098aea916543)

WDYT?

**Comment by h1alexbel** [comment]
@l3r8yJ I'm also can make a second version of diagram

It will be about "How I see the design of such system"

**Comment by l3r8yJ** [comment]
@h1alexbel yeah, sure go ahead

**Comment by l3r8yJ** [comment]
@h1alexbel looks cool, I think we can create a lot of issues using this diagram

**Comment by h1alexbel** [comment]
@l3r8yJ I will create some

**Comment by h1alexbel** [comment]
After diagram decomposition I got:

issues for `bot`:
https://github.com/Blamer-io/bot/issues/57
https://github.com/Blamer-io/bot/issues/58

issues for `hub`:
https://github.com/Blamer-io/hub/issues/19
https://github.com/Blamer-io/hub/issues/20
https://github.com/Blamer-io/hub/issues/21
https://github.com/Blamer-io/hub/issues/22

issues for `notifications`:
skeleton +
https://github.com/Blamer-io/notifications/issues/3

**Comment by h1alexbel** [comment]
also #23
