### ISSUE TITLE
database options

### ISSUE THREAD

**Issue by h1alexbel** [Blamer-io/hub#19]
as we discussed [here](https://github.com/Blamer-io/hub/issues/18), we need a database

so, we need to pick the database type

**Comment by l3r8yJ** [comment]
@h1alexbel So we have several options.

in sql we can use postgresql, in nosql we can use, I don't know, anything, like mongo or graphql, etc.
wdyt

**Comment by h1alexbel** [comment]
@l3r8yJ I think we can try PostgreSQL, simple relational database, in case of logic scalability we can add new tables and objects

WDYT?

**Comment by l3r8yJ** [comment]
@h1alexbel agree with you, i'll create an issue

**Comment by h1alexbel** [comment]
OK, PostgreSQL
