### ISSUE TITLE
database schema

### ISSUE THREAD

**Issue by h1alexbel** [Blamer-io/hub#24]

**Comment by h1alexbel** [comment]
since we need to put the token (encrypted) and related chat id

Chat ID: should be unique, since it represents real Telegram Chat, and Not NULL, of course
Token: We don't need to care about it's uniqueness, but also should be Not NULL

Also, some users can have more than one Token, so -> `Chat ID 1:M Token`

cc @l3r8yJ

**Comment by l3r8yJ** [comment]
@h1alexbel to be honest, I don't see a scenario where one user wants to have multiple gh tokens. Could you please explain this in more detail?

**Comment by h1alexbel** [comment]
@l3r8yJ user can have multiple github accounts for himself and for work for example

WDYT?

**Comment by h1alexbel** [comment]
@l3r8yJ I create liquibase scripts for this

**Comment by l3r8yJ** [comment]
@h1alexbel sure, go ahead, but before you do, please create an issue

**Comment by h1alexbel** [comment]
#33 created

**Comment by h1alexbel** [comment]
the schema in development right now, but initial one is upstream
